#!/usr/bin/env node

'use strict';

var cp = require('child_process');
var args = process.argv.slice(2);
if (/^0/.test(String(process.versions.node))) {
  args.unshift('--harmony');
}
cp.spawn('node', args, { stdio: 'inherit' });
